<?

AnemicClassCreator::create(
    'Employee',
    [
        new AutoGeneratedField(
            'id', '$validators->getIntegerValidator()'),
        new AutoGeneratedField(
            'name', '$validators->getStringValidator()'),
        new AutoGeneratedField(
            'currentlyWorking', '$validators->getBooleanValidator()')
    ]);

// You have magic setters and getters
// getId() , setId(), getName()
// Validation is not explicit
// Class are loaded via an autoloader

$john = new Employee;
$john->setId(1);
$john->setName('John');
$john->setCurrentlyWorking(true);

$john->getName(); 
// returns 'John'